### ISSUE TITLE
Test/upgrade for Laravel 5.6

### ISSUE THREAD

**Issue by bert-w** [Te-cho/compile-blades#4]
Currently the package only supports 5.4 it seems.

**Comment by abidulrmdn** [comment]
created a PR for it. #8

**Comment by abidulrmdn** [comment]
Done and merged to develop

**Comment by abidulrmdn** [comment]
closing this issue now

**Comment by abidulrmdn** [comment]
https://github.com/Te-cho/compile-blades/pull/8
